import os
import uuid
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from PIL import Image


def split_text(text, max_chars=90):
    words = text.split()
    lines = []
    current = ""
    for w in words:
        if len(current) + len(w) + 1 <= max_chars:
            current += (" " if current else "") + w
        else:
            lines.append(current)
            current = w
    if current:
        lines.append(current)
    return lines


def generate_patient_report(response_data):
    """
    Generates PDF report for diagnosis result and returns path.
    Includes Grad-CAM image inside the PDF (if available).
    """

    os.makedirs("reports", exist_ok=True)

    filename = f"report_{uuid.uuid4().hex}.pdf"
    report_path = os.path.join("reports", filename)

    c = canvas.Canvas(report_path, pagesize=letter)
    width, height = letter

    # -------------------------
    # Header
    # -------------------------
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "Smart HealthAI - Diagnosis Report")

    c.setFont("Helvetica", 11)
    c.drawString(50, height - 80, f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    y = height - 130
    line_gap = 20

    def write_line(label, value):
        nonlocal y
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, f"{label}:")
        c.setFont("Helvetica", 12)
        c.drawString(200, y, str(value))
        y -= line_gap

    # -------------------------
    # Diagnosis Info
    # -------------------------
    write_line("Image Prediction", response_data.get("image_prediction", "N/A"))
    write_line("Confidence", response_data.get("image_confidence", "N/A"))

    if response_data.get("pneumonia_type"):
        write_line("Pneumonia Type", response_data.get("pneumonia_type"))

    # -------------------------
    # Recommendation (wrapped)
    # -------------------------
    if response_data.get("recommendation"):
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Recommendation:")
        y -= line_gap

        c.setFont("Helvetica", 12)
        rec = response_data.get("recommendation")
        for line in split_text(rec, max_chars=90):
            c.drawString(60, y, line)
            y -= line_gap

    # -------------------------
    # Grad-CAM Image Embed
    # -------------------------
    gradcam_path = response_data.get("gradcam_image")

    if gradcam_path:
        # Ensure correct file path
        # gradcam_path comes like: "static/gradcam/gradcam_xxx.png"
        abs_gradcam_path = os.path.join(os.getcwd(), gradcam_path.replace("/", os.sep))

        y -= 20
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Grad-CAM Explainability:")
        y -= 20

        if os.path.exists(abs_gradcam_path):
            try:
                # Resize image to fit PDF
                img = Image.open(abs_gradcam_path)
                img_width, img_height = img.size

                # Maximum image area in pdf
                max_w = 400
                max_h = 250

                scale = min(max_w / img_width, max_h / img_height)
                new_w = img_width * scale
                new_h = img_height * scale

                # Draw image
                c.drawImage(
                    ImageReader(img),
                    70, y - new_h,
                    width=new_w,
                    height=new_h
                )

                y = y - new_h - 20

            except Exception as e:
                c.setFont("Helvetica", 11)
                c.drawString(60, y, f"⚠️ Could not embed Grad-CAM image: {str(e)}")
                y -= 20
        else:
            c.setFont("Helvetica", 11)
            c.drawString(60, y, "⚠️ Grad-CAM image not found to embed in report.")
            y -= 20

    # -------------------------
    # Footer Disclaimer
    # -------------------------
    y -= 40
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y, "Disclaimer: This report is generated by an AI model and is for informational purposes only.")
    y -= 15
    c.drawString(50, y, "Always consult a certified doctor for clinical diagnosis and treatment.")

    c.save()

    return report_path
